-- MySQL Script generated by MySQL Workbench
-- Wed Nov  6 12:24:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `address_carrer` VARCHAR(45) NOT NULL,
  `address_numero` VARCHAR(45) NOT NULL,
  `address_pis` VARCHAR(45) NULL,
  `address_porta` VARCHAR(45) NULL,
  `address_ciutat` VARCHAR(45) NOT NULL,
  `address_cp` VARCHAR(45) NOT NULL,
  `address_pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proveïdor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveïdor` (
  `proveïdor_id` INT NOT NULL AUTO_INCREMENT,
  `proveïdor_nom` VARCHAR(45) NULL,
  `proveïdor_tel` INT(9) NULL,
  `proveïdor_fax` INT(10) NULL,
  `proveïdor_NIF` VARCHAR(9) NOT NULL,
  `address_address_id` INT NOT NULL,
  PRIMARY KEY (`proveïdor_id`, `address_address_id`),
  UNIQUE INDEX `proveïdor_NIF_UNIQUE` (`proveïdor_NIF` ASC) VISIBLE,
  INDEX `fk_proveïdor_address1_idx` (`address_address_id` ASC) VISIBLE,
  CONSTRAINT `fk_proveïdor_address1`
    FOREIGN KEY (`address_address_id`)
    REFERENCES `mydb`.`address` (`address_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ulleres` (
  `ulleres_id` INT NOT NULL AUTO_INCREMENT,
  `ulleres_marca` VARCHAR(20) NOT NULL,
  `ulleres_graduació` DECIMAL(4) NULL,
  `ulleres_tipus` ENUM('flotant', 'pasta', 'metàl·lic') NOT NULL,
  `ulleres_colorMuntura` VARCHAR(15) NULL,
  `ulleres_colorVidre` VARCHAR(15) NULL,
  `ulleres_preu` DOUBLE NOT NULL,
  `proveïdor_proveïdor_id` INT NOT NULL,
  PRIMARY KEY (`ulleres_id`),
  INDEX `fk_ulleres_proveïdor1_idx` (`proveïdor_proveïdor_id` ASC) VISIBLE,
  CONSTRAINT `fk_ulleres_proveïdor1`
    FOREIGN KEY (`proveïdor_proveïdor_id`)
    REFERENCES `mydb`.`proveïdor` (`proveïdor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `client_id` INT NOT NULL AUTO_INCREMENT,
  `client_nom` VARCHAR(45) NOT NULL,
  `client_telefon` VARCHAR(9) NULL,
  `client_correu` VARCHAR(45) NULL,
  `client_dataregistre` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `client_client_id` INT NOT NULL,
  `address_address_id` INT NOT NULL,
  PRIMARY KEY (`client_id`, `address_address_id`),
  UNIQUE INDEX `client_correu_UNIQUE` (`client_correu` ASC) VISIBLE,
  INDEX `fk_client_client_idx` (`client_client_id` ASC) VISIBLE,
  INDEX `fk_client_address1_idx` (`address_address_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_client`
    FOREIGN KEY (`client_client_id`)
    REFERENCES `mydb`.`client` (`client_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_client_address1`
    FOREIGN KEY (`address_address_id`)
    REFERENCES `mydb`.`address` (`address_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleats` (
  `empleats_id` INT NOT NULL AUTO_INCREMENT,
  `empleats_nom` VARCHAR(45) NOT NULL,
  `empleats_telefon` VARCHAR(45) NOT NULL,
  `empleats_correu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`empleats_id`),
  UNIQUE INDEX `empleats_correu_UNIQUE` (`empleats_correu` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venta` (
  `venta_id` INT NOT NULL AUTO_INCREMENT,
  `venta_data` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `client_client_id` INT NOT NULL,
  `empleats_empleats_id` INT NOT NULL,
  `ulleres_ulleres_id` INT NOT NULL,
  PRIMARY KEY (`venta_id`),
  INDEX `fk_venta_client1_idx` (`client_client_id` ASC) VISIBLE,
  INDEX `fk_venta_empleats1_idx` (`empleats_empleats_id` ASC) VISIBLE,
  INDEX `fk_venta_ulleres1_idx` (`ulleres_ulleres_id` ASC) VISIBLE,
  CONSTRAINT `fk_venta_client1`
    FOREIGN KEY (`client_client_id`)
    REFERENCES `mydb`.`client` (`client_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_venta_empleats1`
    FOREIGN KEY (`empleats_empleats_id`)
    REFERENCES `mydb`.`empleats` (`empleats_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_venta_ulleres1`
    FOREIGN KEY (`ulleres_ulleres_id`)
    REFERENCES `mydb`.`ulleres` (`ulleres_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
